Иванова Екатерина Александровна

БСБ25-01

Задание 4. Импорт, преобразование и экспорт данных
средствами Pandas

In [3]:
import pandas as pd
import numpy as np

In [2]:
data = "https://raw.githubusercontent.com/EvgeniiSopovGitHub/datasets_uni/refs/heads/main/okaivd/lab_4_raw_data.csv"
df = pd.read_csv(data, sep=';', index_col=0, parse_dates=True)
df.head()

,unit_01,unit_02,unit_03,unit_04,unit_05,unit_06,unit_07,unit_08,unit_09,unit_10
date,,,,,,,,,,
2022-01-01,NaN,35.356841,29.501120,49.620615,33.370093,38.610154,34.559279,53.436849,41.238733,58.494774
2022-01-02,37.112475,49.944375,42.270097,51.557284,NaN,37.078793,22.265877,45.772941,75.733055,53.659106
2022-01-03,NaN,28.340224,48.018449,NaN,39.209601,46.690520,25.886239,31.383527,78.607074,NaN
2022-01-04,50.000000,43.555570,36.278831,43.076333,NaN,35.764313,59.110809,NaN,39.244188,66.407508
2022-01-05,42.434209,28.734675,35.919586,49.739334,37.639153,NaN,15.093752,50.664648,48.536941,65.719188

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 365 entries, 2022-01-01 to 2022-12-31
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   unit_01  326 non-null    float64
 1   unit_02  320 non-null    float64
 2   unit_03  328 non-null    float64
 3   unit_04  330 non-null    float64
 4   unit_05  329 non-null    float64
 5   unit_06  321 non-null    float64
 6   unit_07  326 non-null    float64
 7   unit_08  324 non-null    float64
 8   unit_09  324 non-null    float64
 9   unit_10  340 non-null    float64
dtypes: float64(10)
memory usage: 31.4 KB

In [6]:
mean_values = df.mean()
df = df.fillna(mean_values)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 365 entries, 2022-01-01 to 2022-12-31
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   unit_01  365 non-null    float64
 1   unit_02  365 non-null    float64
 2   unit_03  365 non-null    float64
 3   unit_04  365 non-null    float64
 4   unit_05  365 non-null    float64
 5   unit_06  365 non-null    float64
 6   unit_07  365 non-null    float64
 7   unit_08  365 non-null    float64
 8   unit_09  365 non-null    float64
 9   unit_10  365 non-null    float64
dtypes: float64(10)
memory usage: 31.4 KB

In [8]:
df.isnull().sum()

unit_01    0
unit_02    0
unit_03    0
unit_04    0
unit_05    0
unit_06    0
unit_07    0
unit_08    0
unit_09    0
unit_10    0
dtype: int64

In [9]:
unit_cols = [f'unit_{i:02d}' for i in range(1, 11)]
df[unit_cols] = df[unit_cols].fillna(df[unit_cols].mean())

In [10]:
df.isnull().sum()

unit_01    0
unit_02    0
unit_03    0
unit_04    0
unit_05    0
unit_06    0
unit_07    0
unit_08    0
unit_09    0
unit_10    0
dtype: int64

In [11]:
df['min'] = df[unit_cols].min(axis=1)
df['median'] = df[unit_cols].median(axis=1)
df['max'] = df[unit_cols].max(axis=1)

In [19]:
def mean_std_str(row):
    m = row[unit_cols].mean()
    s = row[unit_cols].std()
    return f"{m:.2f}/{s:.2f}"
df['mean/std'] = df.apply(mean_std_str, axis=1)

In [13]:
df.index = df.index.strftime('%Y-%m-%d')

In [14]:
numeric_cols = unit_cols + ['min', 'median', 'max']
avg_row = df[numeric_cols].mean()
df.loc['average annual'] = avg_row
df.loc['average annual', 'mean/std'] = np.nan

In [16]:
df.head()

,unit_01,unit_02,unit_03,unit_04,unit_05,unit_06,unit_07,unit_08,unit_09,unit_10,min,median,max,mean/std
date,,,,,,,,,,,,,,
2022-01-01,39.713383,35.356841,29.501120,49.620615,33.370093,38.610154,34.559279,53.436849,41.238733,58.494774,29.501120,39.161769,58.494774,41.39/9.46
2022-01-02,37.112475,49.944375,42.270097,51.557284,40.549544,37.078793,22.265877,45.772941,75.733055,53.659106,22.265877,44.021519,75.733055,45.59/13.96
2022-01-03,39.713383,28.340224,48.018449,39.977347,39.209601,46.690520,25.886239,31.383527,78.607074,60.231050,25.886239,39.845365,78.607074,43.81/15.90
2022-01-04,50.000000,43.555570,36.278831,43.076333,40.549544,35.764313,59.110809,49.864199,39.244188,66.407508,35.764313,43.315951,66.407508,46.39/10.04
2022-01-05,42.434209,28.734675,35.919586,49.739334,37.639153,39.931516,15.093752,50.664648,48.536941,65.719188,15.093752,41.182863,65.719188,41.44/13.73

In [17]:
df.tail()

,unit_01,unit_02,unit_03,unit_04,unit_05,unit_06,unit_07,unit_08,unit_09,unit_10,min,median,max,mean/std
date,,,,,,,,,,,,,,
2022-12-28,36.922681,42.956541,37.757330,39.423959,40.549544,42.500627,47.705860,30.529000,46.644630,60.888610,30.529000,41.525086,60.888610,42.59/8.12
2022-12-29,39.835742,30.958749,41.143042,46.283822,40.549544,35.878442,64.125878,52.910647,76.109909,65.518039,30.958749,43.713432,76.109909,49.33/14.81
2022-12-30,34.484518,36.817061,26.891212,40.649628,34.485905,39.078600,60.788903,48.904611,66.273623,67.848695,26.891212,39.864114,67.848695,45.62/14.55
2022-12-31,28.044285,38.053724,50.317334,46.277700,44.742887,35.568732,69.927246,56.475326,73.268611,63.756814,28.044285,48.297517,73.268611,50.64/15.06
average annual,39.713383,39.598905,40.309659,39.977347,40.549544,39.931516,37.464036,49.864199,55.345836,60.231050,28.343891,41.811193,65.371048,NaN

In [18]:
df.to_csv("lab4_bsb_ivanova.csv",index=True)